### ISSUE TITLE
unhandled `{ssl_closed, _}` message when using `async`

### ISSUE THREAD

**Issue by paulswartz** [benoitc/hackney#464]
I see the following message in my Elixir logs periodically:
```
Unexpected message: {:ssl_closed, {:sslsocket, {:gen_tcp, #Port<0.9056>, :tls_connection, :undefined}, #PID<0.10027.10>}}
```

That looks like a close message from the SSL socket, which I'd expect hackney to manage the same as a close of the TCP connection (which are handled properly). I'm using the `async` option to stream the response data as it comes in.

**Comment by matthewoden** [comment]
I can reproduce this - I'm also using the async library. It seems that my chunk gets mixed in with it, as the last argument.

```Unexpected message: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.8780>, :tls_connection, :undefined}, #PID<0.380.0>}, <<250, 148, 222, 99, 116, 39, 82, 167, 182, 77, 245, 137, 189, 33, 60, 168, 182, 240, 30, 55, 235, 210, 208, 103, 217, 48, 245, 8, 29, 92, 27, 76, 134, 173, 101, 105, 228, 74, 31, 239, 5, 67, 94, 174, 203, 215, 11, 155, ...>>}```

**Comment by benoitc** [comment]
hrm it's probably happening on close. @paulswartz is your code similar to the one posted by @matthewoden ?

**Comment by paulswartz** [comment]
I'm using hackney via [httpoison](https://hex.pm/packages/httpoison), but here's the relevant code: https://github.com/edgurgel/httpoison/blob/master/lib/httpoison/base.ex#L369-L387

**Comment by matthewoden** [comment]
If it matters, I've done a quick port on my code over to `:ibrowse`, and the issue hasn't come up again. The receive block is basically the same (though ibrowse combines status and headers into a single message). 

I'd prefer to use hackney, so just let me know if you need any other usage info.

**Comment by benoitc** [comment]
well the issue is that a message is still on the process heap after cloising the socket. I have a fix for it. Will take care of it later today. Thanks for the code!

**Comment by benoitc** [comment]
can you try #482?

**Comment by benoitc** [comment]
can anyone provides me a link on which I can reproduce the issue?

**Comment by matthewoden** [comment]
I can't provide our source, but I'll see if I can get #482 out in a test environment today or tomorrow.

**Comment by stephenmoloney** [comment]
This `https://github.com/stephenmoloney/fastimage/pull/24` reproduces it everytime.

**Comment by benoitc** [comment]
@stephenmoloney do you mean the link? I need to reporduce it apart of the another lib ...

**Comment by stephenmoloney** [comment]
@benoitc sorry, I don't full understand... When the tests run, that error is printed... 

`https://travis-ci.org/stephenmoloney/fastimage/jobs/346210674`

I still didn't get time to try the tracing.

**Comment by critch** [comment]
@benoitc Take your example of async receiving in the documentation, convert to require stream_next, and put a sleep of a second or more between requesting stream_next. This is how I have done it via elixir with only hackney. There is something possibly a race condition of receiving the last of the web request and the receiving a message to stream_next. The stream has fully closed, but the buffer has not been flushed out and the done message sent.

**Comment by benoitc** [comment]
@critch thanks. Quite possible indeed. I think that rather than pausing i should rather receive actively at some point. I will have a closer looks, thanks for the reproducible way.

**Comment by benoitc** [comment]
fixed in latest master.

**Comment by rozap** [comment]
I still see this happening with hackney `1.12.1`. It definitely seems to be a race condition, as it happens sometimes.

One thing I don't understand from `d4c4f3930d633a675a4224eb76149646c1e6cd74` is that the changes all seem to be around closing the socket, but I see this error happen long before the socket has closed - just after the response stream starts. 

I'm going to keep looking into it.

**Comment by rozap** [comment]
I've got two traces, one where it works and one where it crashes.

This is part of the working trace that differs from the broken one. 
```
13:20:52:826799 (<0.931.0>) << {#Ref<0.3355659064.3830185990.130707>,stream_next}
13:20:52:826812 (<0.931.0>) << {#Ref<0.3355659064.3830185990.130707>,stream_next}
13:20:52:826826 (<0.931.0>) <0.929.0> ! {'$gen_call',
                                            {<0.931.0>,#Ref<0.3355659064.3830185990.130819>},
                                            {set_opts,[{active,once}]}}
13:20:52:826862 (<0.931.0>) << {#Ref<0.3355659064.3830185990.130819>,ok}
13:20:52:826869 (<0.931.0>) <0.929.0> ! {'$gen_call',
                                            {<0.931.0>,#Ref<0.3355659064.3830185990.130820>},
                                            {set_opts,[{active,once}]}}
13:20:52:826901 (<0.931.0>) << {#Ref<0.3355659064.3830185990.130820>,ok}
13:20:52:827039 (<0.931.0>) << {ssl,{sslsocket,{gen_tcp,#Port<0.27730>,tls_connection,undefined},
                                               <0.929.0>},
```

This is the broken one
```
13:06:37:122289 (<0.1064.0>) << {#Ref<0.280439725.1680343042.127415>,stream_next}
13:06:37:122300 (<0.1064.0>) << {#Ref<0.280439725.1680343042.127415>,stream_next}
13:06:37:122332 (<0.1064.0>) <0.1062.0> ! {'$gen_call',
                                              {<0.1064.0>,#Ref<0.280439725.1680343041.134667>},
                                              {set_opts,[{active,once}]}}
13:06:37:122368 (<0.1064.0>) << {#Ref<0.280439725.1680343041.134667>,ok}
13:06:37:122547 (<0.1064.0>) <0.1062.0> ! {'$gen_call',
                                              {<0.1064.0>,#Ref<0.280439725.1680343041.134668>},
                                              {set_opts,[{active,once}]}}
13:06:37:122562 (<0.1064.0>) << {ssl,{sslsocket,{gen_tcp,#Port<0.28349>,tls_connection,undefined},
                                                <0.1062.0>},
```

If you look at them side by side, we see the working one has 
```
13:20:52:826869 (<0.931.0>) <0.929.0> ! {'$gen_call',
                                            {<0.931.0>,#Ref<0.3355659064.3830185990.130820>},
                                            {set_opts,[{active,once}]}}
13:20:52:826901 (<0.931.0>) << {#Ref<0.3355659064.3830185990.130820>,ok}
```
But the broken one is missing that `ok` response from setting the transport opts - its next message is the first chunk of data. 

So I think the `Transport:setopts(TSock, [{active, once}]),` line in `hackney_stream.erl` is maybe not blocking until it receives the `ok`?

**Comment by rozap** [comment]
Just going to leave a comment here if anyone else encounters this behavior: the reason for this seemed to be calling `stream_next` twice in a row without waiting for an ack after the socket was set up. Removing the duplicate call I had seems to have fixed it.

**Comment by benoitc** [comment]
@rozap you mean 2 consecutive call without receiving the message? can you show a simple snippet for it?

just fyi  right after the next release i will revisit the stream code to make it simpler to handle, but if we can fix that issue firsy/

**Comment by rozap** [comment]
I mean in my app code, I was accidentally calling stream_next twice without receiving a message, yes. A snippet probably won't be super useful, because there is some complexity about my app mixed in there :)

**Comment by billgloff** [comment]
Any updates on this as I'm still seeing this behavior in version 1.14.3?

**Comment by benoitc** [comment]
@billgloff how does it happen? Can you open a ticket with more details if you can?

**Comment by paulswartz** [comment]
I'm also seeing this again; it appears to have started in earnest after updating to Erlang 21.2. I don't have more information at the moment but I'm investigating on my end.

**Comment by dbhobbs** [comment]
We've also started seeing this error in our logs after an update to Erlang 21.2

`{:ssl_closed, {:sslsocket, {:gen_tcp, #Port<0.1490365>, :tls_connection, :undefined}, [#PID<0.21817.64>, #PID<0.21816.64>]}}`

**Comment by paulswartz** [comment]
It does seem related to that. There's a PR which may address it: https://bugs.erlang.org/browse/ERL-371

**Comment by binarylogic** [comment]
@dbhobbs we are experiencing the same issue, did you find a work around? I can also confirm this is specific to `21.2`, `21.1` does not have this issues.

@paulswartz that change, unfortunately, did not resolve the error. I have tested `21.2.5`, `21.2.4`, `21.2.3`, and `21.2.2`, all of which encounter this error.

I'm curious if anyone else has a fix or workaround?

**Comment by paulswartz** [comment]
@binarylogic We haven't found a fix/workaround. Our application fetches very frequently (every few seconds) so having some prematurely closed connections is manageable.

**Comment by dbhobbs** [comment]
@binarylogic we have not found a workaround. Fortunately for us the error occurs in our pubsub connection, so we just receive the message again after it fails. I've been waiting for a chance to update to 21.2.5 to see if that mitigates the issue at all.

**Comment by benoitc** [comment]
@binarylogic do you have a simple way to reproduce it? maybe a simple snippet showing  how the async request is handled is enough

**Comment by bblaszkow06** [comment]
Hi @benoitc! I'm also having this issue. I think it's time to reopen it :wink: 
Anyway, here's the snippet that reproduces the problem (disclaimer - I don't know Erlang, so it's in Elixir):
```elixir
iex(1)> url = "https://www.openssl.org/source/openssl-1.1.1a.tar.gz"
iex(2)> {:ok, resp} = :hackney.get(url, [], "", async: :once)
{:ok, #Reference<0.3880280478.3613130753.31696>}
iex(3)> :hackney.stream_next(resp)
:ok
iex(4)> :hackney.stream_next(resp)
:ok
iex(5)> :hackney.stream_next(resp)
:ok
iex(6)> flush
{:hackney_response, #Reference<0.3880280478.3613130753.31696>,
 {:status, 200, "OK"}}
{:hackney_response, #Reference<0.3880280478.3613130753.31696>,
 {:headers,
  [
    {"Server", "Apache/2.4.18 (Ubuntu)"},
    {"Strict-Transport-Security",
     "max-age=31536000; includeSubDomains; preload"},
    {"Last-Modified", "Tue, 20 Nov 2018 14:07:08 GMT"},
    {"ETag", "\"7f6b53-57b192634f900\""},
    {"Accept-Ranges", "bytes"},
    {"Content-Length", "8350547"},
    {"Content-Type", "application/x-gzip"},
    {"Cache-Control", "max-age=165527"},
    {"Expires", "Thu, 14 Feb 2019 09:33:40 GMT"},
    {"Date", "Tue, 12 Feb 2019 11:34:53 GMT"},
    {"Connection", "keep-alive"}
  ]}}
{:hackney_response, #Reference<0.3880280478.3613130753.31696>,
 <<31, 139, 8, 0, 174, 13, 244, 91, 2, 3, 236, 60, 127, 119, 218, 198, 178, 249,
   183, 124, 138, 45, 166, 137, 192, 24, 16, 254, 153, 56, 164, 37, 14, 73, 124,
   74, 192, 199, 198, 77, 251, 156, 148, 35, 164, 5, 84, ...>>}
{:hackney_response, #Reference<0.3880280478.3613130753.31696>,
 <<147, 53, 108, 2, 227, 253, 48, 30, 63, 212, 126, 235, 87, 254, 121, 152, 74,
   51, 93, 253, 58, 46, 13, 49, 217, 130, 184, 152, 68, 224, 225, 72, 208, 120,
   188, 4, 180, 85, 245, 47, 61, 115, 63, 121, 168, 218, 190, ...>>}
:ok

# Now wait for up to 10 minutes

12:43:14.870 [error] Unexpected message: {:ssl_closed, {:sslsocket, {:gen_tcp,
 #Port<0.1468>,tls_connection, :undefined}, [#PID<0.1063.0>, #PID<0.1062.0>]}}
iex(7)> :hackney.stream_next(resp)                       
{:error, :req_not_found}
```
This is Elixir 1.8 and OTP 21.2.3. I've managed to trace this message, it is received here:
https://github.com/benoitc/hackney/blob/2f55c0d37f9d5942b976272a1df5adecca4edc61/src/hackney_stream.erl#L152

There was a fix in OTP 21.2.3 (https://bugs.erlang.org/browse/ERL-371) in `ssl` application that prevents sending the `:ssl_closed` message before all the data was sent, that's why there are `stream_next` calls in the snippet above - the next message was supposed to be `{:hackney_response, _, :done}` and since 21.2.3 only then is the `:ssl_closed` message received. Before that version, the response could be closed before getting all the data.

**Comment by bblaszkow06** [comment]
One more detail: there's no need to wait 10mins for `:ssl_closed` if there's no {"Connection", "keep-alive"} header.
```elixir
url = "https://download.fedoraproject.org/pub/fedora/linux/releases/29/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-29-1.2.iso"
"https://download.fedoraproject.org/pub/fedora/linux/releases/29/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-29-1.2.iso"
iex(34)> {:ok, resp} = :hackney.get(url, [], "", async: :once)
{:ok, #Reference<0.1509818611.3649830913.19500>}
iex(35)> :hackney.stream_next(resp)

# 15 seconds later

16:08:12.738 [error] Unexpected message: {:ssl_closed, {:sslsocket, {:gen_tcp, #Port<0.24>, 
:tls_connection, :undefined}, [#PID<0.319.0>, #PID<0.318.0>]}}
```

**Comment by benoitc** [comment]
thanks for the log. I think I know what’s going on. I will try a fix later today. cc  @bblaszkozwO6

**Comment by binarylogic** [comment]
@benoitc do you mind sharing what you know? Maybe one of us can help? We're waiting on this fix as well. Happy to help if we can.

**Comment by benoitc** [comment]
@binarylogicsorry got side tracked.  i think the socket isn't released during the redirection, but I may have to check. Also i also need to check if messages are flushed during close. I will have a look tomorrow.

**Comment by tpitale** [comment]
I'm using OTP 21.3.3 and could not reproduce using @bblaszkow06 example script. But … I have seen these messages popping up unhandled. I'll continue to dig and see what I can find, if anything new.

**Comment by shonfeder** [comment]
@benoitc or @tpitale, have either of you discovered anything through your investigations so far? We seem to have an acute case of this cluttering our logs. Is there anything in particular I can do to help investigate or work towards a fix?

**Comment by tpitale** [comment]
I haven’t, sorry.

**Comment by benoitc** [comment]
there is a new version planned this month. I will recheck. Also the coming 2.0 in june will only support erlang >= 21.

**Comment by balexand** [comment]
I see this consistently with Erlang 21.3.8. It's coming from calls to `ExAws`, which uses `HTTPoison`, which uses `hackney`. I'm working around the issue by calling `ExAws` in a temporary process (Elixir `Task`).

**Comment by adamkittelson** [comment]
Is there any harm in just working around this by just handling the message in the process that receives it for now?

`def handle_info({:ssl_closed, _msg}, state), do: {:noreply, state}`

In other words is unexpectedly receiving this message the only real fallout of the problem or is it just a symptom of a larger issue? I'm getting this on a QA server where I've upgraded from Erlang 19.x to 22.0.1 and want to know if this is something I should wait for a fix for before considering moving to production or if it's fine to just handle the message until a fix is released.

**Comment by chulkilee** [comment]
Still having this issue with hackney 1.15.1 via tesla 1.2.1 on elixir 1.8.2-otp-22, otp 22.0.4 (mac), when I use hackney from GenServer.

Tesla is not using async - just use `:hackney.request/5` - see [tesla code](https://github.com/teamon/tesla/blob/v1.2.1/lib/tesla/adapter/hackney.ex#L69) 

For now, I'm just adding `handle_info` to the GenServer (as suggested in the previous comment).

However, is this a issue on OTP, or hackeny? Even it's an OTP issue, I think hackney should not pass the message back to the caller, if async is not used. Not sure that's possible though.

**Comment by nulian** [comment]
Same thing also with non async request as long as you are doing it in a different genserver then the base one it seems you have a chance of this occurring.

**Comment by joshchernoff** [comment]
Seen with 
hackney  1.15.1
elixir         1.9.0
erlang      22.0.5

**Comment by spieker** [comment]
I get the same error with

hackney 1.15.1
elixir 1.9.0
erlang 22.0.7

It works with

hackney 1.15.1
elixir 1.6.5
erlang 20.3.8.22

**Comment by paveltyk** [comment]
Leaking messages with:

Elixir 1.8.2
OTP 21.3.8.6
HTTPoison 1.5.1
Hackney 1.15.1

**Comment by palimarrao** [comment]
Leaking messages with:

Elixir 1.9.2
OTP 22.1
HTTPoison 1.5.0
Hackney 1.15.1

If it makes sense, I can take a look at it. Also, is there any pattern of usage that sidesteps the issue?

**Comment by astutecat** [comment]
We're getting this when using it with `oc_reporter` (see @bipthelin 's PR above from september)  - the failures are happening frequently enough that it brings down the VM. We're keem to see a fix for this too.

**Comment by bipthelin** [comment]
> We're getting this when using it with `oc_reporter` (see @bipthelin 's PR above from september) - the failures are happening frequently enough that it brings down the VM. We're keem to see a fix for this too.

This commit fixed it for us: https://github.com/opencensus-beam/oc_google_reporter/commit/bb578a5de7b3d986d77e4ad093ae0b82e220c22d

It seems that if you don't close hackney either explicitly with `hackney:close(Ref)` or implicitly by reading the body the pool will eventually get exhausted. This seems to be a problem in how `hackney` get's invoked and it should probably be some info about it on the `README`

**Comment by furqanaziz** [comment]
Hi @benoitc 
any update about
`Unexpected message: {:ssl_closed, {:sslsocket, {:gen_tcp, #Port<0.9056>, :tls_connection, :undefined}, #PID<0.10027.10>}}`

**Comment by rbino** [comment]
Hi @benoitc,
I just came across this bug in a production system while using HTTPoison, is it fixed in new hackney versions or is it still an open bug?

**Comment by rozap** [comment]
Fix submitted as https://github.com/benoitc/hackney/pull/640
